spring.application.name=finance


spring.profiles.active=dev


spring.config.import=optional:classpath:env/env.dev.properties

ecb.sync.enabled=true
ecb.sync.initial-load=false

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true