server {
    listen 80;
    server_name api.tarasantoniuk.com;

    location / {
        proxy_pass http://finance-core-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Для Certbot можна підключити webroot одразу
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}