services:
  db:
    image: postgres:17-alpine
    container_name: finance-core-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: finance-core-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/finance_db
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: test_password
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: finance-core-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d   # тільки конфігурації
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # якщо є свій nginx.conf
      - ./certs:/etc/letsencrypt           # для сертифікатів
      - ./logs/nginx:/var/log/nginx

volumes:
  db_data:
