version: "3.9"

services:
  finance-core-db:
    image: postgres:17-alpine
    container_name: finance-core-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  finance-core-app:
    image: eclipse-temurin:21-jre-alpine
    container_name: finance-core-app
    restart: always
    depends_on:
      finance-core-db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: >
      sh -c "
      echo 'Waiting for DB...' &&
      sleep 10 &&
      java -jar app.jar
      "
    ports:
      - "8080:8080"

  finance-core-nginx:
    image: nginx:alpine
    container_name: finance-core-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - finance-core-app

  finance-core-certbot:
    image: certbot/certbot:latest
    container_name: finance-core-certbot
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done"
